### ISSUE TITLE
Code Release Time

### ISSUE THREAD

**Issue by hrwise-nlp** [noewangjy/SP-CoT#1]
Hello, pretty nice work and I am wondering when will the code about data construction will be release?

**Comment by skykiseki** [comment]
same question here

**Comment by liuxiaocs7** [comment]
+1

**Comment by noewangjy** [comment]
Sorry for the late update, I have been occupied by the graduation affairs. The code and scripts have been updated now. If you have any questions or find any bugs, please start a new issue or send me an email. Thanks for you patience and attention :-)

**Comment by liuxiaocs7** [comment]
> Sorry for the late update, I have been occupied by the graduation affairs. The code and scripts have been updated now. If you have any questions or find any bugs, please start a new issue or send me an email. Thanks for you patience and attention :-)

Thanks for your effort and excellent work!
