### ISSUE TITLE
No such file or directory: 'data/self-prompt-cot/pseudo_dataset_raw.json'

### ISSUE THREAD

**Issue by Lllllivia** [noewangjy/SP-CoT#2]
When running "bash run_build_pseudo_dataset.sh," an error occurred.

~/SP-CoT$ bash run_build_pseudo_dataset.sh
Traceback (most recent call last):
  File "tasks/build_pseudo_dataset.py", line 975, in <module>
    filtered_datasets = json.load(open(os.path.join(args.output_dir, "pseudo_dataset_raw.json"), "r"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/self-prompt-cot/pseudo_dataset_raw.json'“

Cannot find the file 'pseudo_dataset_raw.json' in the directory 'data/self-prompt-cot'.

**Comment by noewangjy** [comment]
Hello @Lllllivia , thanks for your sharing your error logs.

I checked the code again, some dependent code in `tasks/build_pseudo_dataset.py` are left commented, so the code did not generated  `pseudo_dataset_raw.json` first. I uncomment the dependent code blocks, it may work now.

Please note that If you want to build a new pseudo dataset via self-generation, DO generate the topics first, then build the pseudo dataset with run_build_pseudo_dataset.sh (default for gpt-3.5-turbo).

If you just want to run SP-CoT with our generated pseudo dataset, the pseudo datasets are already included in the repo: 
- `data/self-prompt-cot/pseudo_dataset.json` generated by `gpt-3.5-turbo-0301`
- `data/self-prompt-cot/pseudo_dataset_$MODEL.json` generated by other MODELs. (e.g. `alpaca` for alpaca-13b)
You can directly start from `run_build_demo_clustering.sh`.

**Comment by Lllllivia** [comment]
> Hello @Lllllivia , thanks for your sharing your error logs.
> 
> I checked the code again, some dependent code in `tasks/build_pseudo_dataset.py` are left commented, so the code did not generated `pseudo_dataset_raw.json` first. I uncomment the dependent code blocks, it may work now.
> 
> Please note that If you want to build a new pseudo dataset via self-generation, DO generate the topics first, then build the pseudo dataset with run_build_pseudo_dataset.sh (default for gpt-3.5-turbo).
> 
> If you just want to run SP-CoT with our generated pseudo dataset, the pseudo datasets are already included in the repo:
> 
> * `data/self-prompt-cot/pseudo_dataset.json` generated by `gpt-3.5-turbo-0301`
> * `data/self-prompt-cot/pseudo_dataset_$MODEL.json` generated by other MODELs. (e.g. `alpaca` for alpaca-13b)
>   You can directly start from `run_build_demo_clustering.sh`.

Thanks a lot for your help.
